#!/bin/bash

##	Purpose: Can be run manually by user, and optionally by boot-time system cron for servers or dedicated miners
##	Notes:
##		- The only reason sudo is needed, is also the only reason these scripts exist at all:
##        to work with cron to auto-start at boot, and restart every hour.
##	History
##		- 20210423 t00mietum: Created.

set -e

echo
echo "Copyright (c) 2021 t00mietum."
echo "License GPLv3+: GNU GPL version 3 or later, full text at:"
echo "    https://www.gnu.org/licenses/gpl-3.0.en.html"
echo "There is no warranty, to the extent permitted by law."
echo
echo "Warning: Mining involves a real risk of physical hardware damage or even"
echo "fire, especially when forcing restarts after heat-related crashes! Please"
echo "investigate why restarts are needed, rule out heat, and be careful."
echo
echo "If this improves your life, XMR donations are welcome at:"
echo "XMR: 8Bie5uuU18eSCc7c9eqWJGh2YMfTRz3og5f2wjqFcGt12ynzLZZvNoqJ5HYs2xuv2nPC8gksmYTCLXHQJLVfNSeUQsBG7Eg"
echo "ETH: 0x925966644EdEc86d0CC1C1cc6165A25A78b91Ba4"
echo "BTC: 1NPgcV7FomPoZNuPQKQ1bLFZHhzCAYNEiS"
echo

## Validate installation
if [[ ! -d /usr/local/bin/et ]]; then echo -e "The 'et-' suite of scripts in not installed correctly. Read 'readme.md'.\n"; exit 1; fi

## Validate sudo
#if [[ "$EUID" != "0"  ]]; then echo -e "Must run as root or sudo.\n"; exit 1; fi

## Get sudo
echo "[ Getting sudo ... ]"
sudo echo "[ Sudo got ... ]"

## Verify or create symlinks
#[[ ! -f  /usr/local/bin/et-interactive  ]]  &&  sudo ln -s  /usr/local/bin/et-interactive  /usr/local/bin/et-interactive
#[[ ! -f  /usr/local/bin/et-start        ]]  &&  sudo ln -s  /usr/local/bin/et/et-start     /usr/local/bin/et-start
#[[ ! -f  /usr/local/bin/et-stop         ]]  &&  sudo ln -s  /usr/local/bin/et/et-start     /usr/local/bin/et-stop

## Mark script as executable so it will run as scheduled (if it is scheduled)
echo "[ Enabling ETH mining auto-restart ... ]"
sudo chmod ugo+x /usr/local/bin/et/et

## Invoke it
echo "[ Starting ETH mining ... ]"
sudo /usr/local/bin/et/et
